### ISSUE TITLE
Issue-1-user-sees-slideshow

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/ajax-project#1]
## 💰 Motivation

The user can see a slide-show of the top 10 most popular cocktails
## 📐 Plan

Create a slide-show showing images of cocktails via API

## ✅ Task List

- [x] Create a modern-style background 
- [x] Create a proper header with links to other parts of the site
- [x] use an API to access the top 10 cocktails
- [x] Use cocktail data to generate a DOM tree for each cocktail
- [x] Use setInterval() to make a slide-show that changes every 2 seconds
- [x] refactor, test for functionality, fix bugs, and delete unnecessary code
