### ISSUE TITLE
Issue-2-user-can-click-slideshow

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/ajax-project#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

user can click on the the current slideshow image for the  particular cocktail recipe or the left/right arrow key to see the next cocktail

## ✅ Task List

- [x] Create  left/right-pointing chevron images on the sides of the slideshow 
- [x] add a click event listener that will rotate to the proper image when fired
- [x] the setInterval should be cleared and then restarted after each click event
- [x] create a button for "Random Cocktail" 
- [x] add a listener to the button so that clicking it will direct user to a random cocktail recipe when clicked
