### ISSUE TITLE
issue-3-user-can-search-first-letter

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/ajax-project#3]
## 💰 Motivation

 User can search for cocktail list by first letter

## 📐 Plan

 User can search for cocktail list by first letter

## ✅ Task List

- [x] Use DOM Delegation to check and see if the user clicked on "Browse" icon  
- [x] After the click, hide all pages and display the "Browse" page
- [x] Create 2 rows of letters (13 letters each row) with anchor link tags
- [x] Each letter that the user click should display a list of cocktails starting with that letter (e.g. clicking A should list items such as "Apple Martini, Apollo, etc"
- [x] Clicking on a cocktail name should lead user to the recipe page
