### ISSUE TITLE
issue-4-user-can-pick-random

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/ajax-project#4]
## 💰 Motivation

 User can choose a random cocktail or click on the current rotating image on the home page to get a recipe
## 📐 Plan

 User can click a button which leads to a random cocktail recipe

## ✅ Task List

- [x] request the whole list of cocktails via API
- [x]  When the user clicks 'Random', show the random page and hide all other pages
- [x] write a function to generate a random integer between 0 and the length of the drinks array
- [x] use the return value of that function as the index in order to grab ingredients & instructions data from the data model
- [x] When the user clicks "random" again, all previous content must be cleared and new content posted
- [x] Allow user to click on rotating images/name on the home page so that it leads them to the recipe page for that particular image/name
