### ISSUE TITLE
issue-5-user-can-learn-about-liquors

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/ajax-project#5]
## 💰 Motivation

 User should be able to learn a bit of information about each type of liquor

## 📐 Plan

 User choose from a list of liquor to learn about its historical background and usage

## ✅ Task List

- [x] when user clicks on 'Info', Info page should be shown and other pages hidden
- [x] The info page should list all available liquors the user can learn about (Gin, Vodka, Bourbon, etc.)
- [x] clicking on a certain liquor should clear all content on the page and display new info about the chosen liquor
- [x] clicking on 'Info' again after viewing a liquor should bring the user back to the info page
